#!/bin/ash
# shellcheck shell=bash

set -e

if [[ \
	-z "${ATACCAMA_ONE_TELLSTORY_WEBAPP_API_BASE_URL}" \
	|| -z "${ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_REALM}" \
	|| -z "${ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_URL}" \
	|| -z "${ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_CLIENT_ID}" \
]]; then
	echo "Missing required environment variable(s). Required variables:"
	echo "ATACCAMA_ONE_TELLSTORY_WEBAPP_API_BASE_URL"
	echo "ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_REALM"
	echo "ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_URL"
	echo "ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_CLIENT_ID"

	exit 1
fi

if [[ "${ATACCAMA_ONE_TELLSTORY_FF_ONE_INTEGRATION}" = "on" ]]; then
	export ATACCAMA_ONE_TELLSTORY_WEBAPP_ONE_INTEGRATION="${ATACCAMA_ONE_TELLSTORY_WEBAPP_ONE_INTEGRATION:-true}"
	export ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_MONITOR_PROJECT="${ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_MONITOR_PROJECT:-true}"
	export ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_CATALOG_ITEM="${ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_CATALOG_ITEM:-true}"
	export ATACCAMA_ONE_TELLSTORY_WEBAPP_CATALOG_URL="${ATACCAMA_ONE_TELLSTORY_WEBAPP_CATALOG_URL}"
fi
if [[ "${ATACCAMA_ONE_TELLSTORY_FF_CRON_UPLOAD_SCHEDULE}" = "on" ]]; then
	export ATACCAMA_ONE_TELLSTORY_WEBAPP_CRON_UPLOAD_SCHEDULE="${ATACCAMA_ONE_TELLSTORY_WEBAPP_CRON_UPLOAD_SCHEDULE:-true}"
fi

if [[ "${ATACCAMA_ONE_TELLSTORY_FF_GOOGLE_SHEETS}" = "on" ]]; then
	if [[ \
		-z "${ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_KEY}" \
		|| -z "${ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_CLIENT_ID}" \
	]]; then
		echo "Can't enable google sheet integration. Required variables:"
		echo "ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_KEY"
		echo "ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_CLIENT_ID"

		exit 1
	fi
fi

if [[ "${ATACCAMA_ONE_TELLSTORY_FF_CUSTOM_RAW_FILTERS}" = "on" ]]; then
	export ATACCAMA_ONE_TELLSTORY_WEBAPP_FILTER_RAW="${ATACCAMA_ONE_TELLSTORY_WEBAPP_FILTER_RAW:-true}"
fi

export ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL="${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL:-/}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL_NO_END_SLASH="${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL%/}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_BASE_URL="${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL}widgets"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_HASH="${ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_HASH:-$(echo $RANDOM | md5sum | head -c 20)}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_INSIGHTS="${ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_INSIGHTS:-true}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_ENVIRONMENT="${ATACCAMA_ONE_TELLSTORY_WEBAPP_ENVIRONMENT:-production}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_HEADER_NAME="${ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_HEADER_NAME:-Authorization}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_TOKEN_TYPE="${ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_TOKEN_TYPE:-Bearer}"
export ATACCAMA_ONE_TELLSTORY_WEBAPP_CATALOG_ITEM_DETAIL_URL_TEMPLATE="${ATACCAMA_ONE_TELLSTORY_WEBAPP_CATALOG_ITEM_DETAIL_URL_TEMPLATE:-/catalog/data/catalogItem/<ID>/}"

export ATACCAMA_ONE_TELLSTORY_MICROSERVICE_NAME="${ATACCAMA_ONE_TELLSTORY_MICROSERVICE_NAME:-DataStoriesFrontend}"
export ATACCAMA_ONE_TELLSTORY_BUSINESS_VERSION="${ATACCAMA_ONE_TELLSTORY_BUSINESS_VERSION:-v0}"
export ATACCAMA_ONE_TELLSTORY_BUILD_ID="${ATACCAMA_ONE_TELLSTORY_BUILD_ID:-latest}"
export ATACCAMA_ONE_TELLSTORY_COMMIT_ID="${ATACCAMA_ONE_TELLSTORY_COMMIT_ID:-000000}"

jq -cnM "$(cat << EndOfConfig
def env2bool: if (. == "true" or . == "on") then true else false end;

{
	"apiBaseUrl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_API_BASE_URL,
	"appBaseUrl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL,
	"widget": {
		"baseUrl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_BASE_URL,
		"hash": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_HASH,
		"showInsights": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_WIDGET_INSIGHTS | env2bool)
	},
	"environment": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_ENVIRONMENT,
	"googleApi": (if (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_KEY != null and env.ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_CLIENT_ID != null) then {
		"apiKey" : env.ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_KEY,
		"clientId" : env.ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_CLIENT_ID
	} else null end),
	"enablePosthog": (env.ATACCAMA_ONE_TELLSTORY_FF_ENABLE_POSTHOG |  env2bool),
	"posthogApiKey": (if (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_POSTHOG_API_KEY != null) then env.ATACCAMA_ONE_TELLSTORY_WEBAPP_POSTHOG_API_KEY else null end),
	"posthogApiUrl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_POSTHOG_API_URL,
	"oneIntegration": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_ONE_INTEGRATION | env2bool),
	"dqCatalogItem": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_CATALOG_ITEM | env2bool),
	"dqMonitorProject": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_MONITOR_PROJECT | env2bool),
	"cronEnabled": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_CRON_UPLOAD_SCHEDULE | env2bool),
	"deckGl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_DECKGL_KEY,
	"denyMaps": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_FEATURE_DENY_MAPS,
	"explorer": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_FEATURE_EXPLORER | env2bool),
	"sharePublicLink": (env.ATACCAMA_ONE_TELLSTORY_WEBAPP_SHARE_PUBLIC_LINK | env2bool),
	"filter": {
		"raw": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_FILTER_RAW
	},
	"auth": {
		"headerName": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_HEADER_NAME,
		"tokenType": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_TOKEN_TYPE,
		"keycloak": {
			"realm": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_REALM,
			"url": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_URL,
			"clientId": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_CLIENT_ID
		}
	},
	"templates": {
   "catalogItemDetailUrl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_CATALOG_ITEM_DETAIL_URL_TEMPLATE,
   "catalogUrl": env.ATACCAMA_ONE_TELLSTORY_WEBAPP_CATALOG_URL
  },
	"versions": {
		"business": env.ATACCAMA_ONE_TELLSTORY_BUSINESS_VERSION,
		"build": env.ATACCAMA_ONE_TELLSTORY_BUILD_ID,
		"commit": env.ATACCAMA_ONE_TELLSTORY_COMMIT_ID,
	}
}
EndOfConfig
)" > /var/www/html/config.json

echo "appBaseUrl = ${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL};" > /var/www/html/config.js

# shellcheck disable=SC2016
envsubst '${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL} ${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL_NO_END_SLASH}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
echo "Using the following config with path (${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL})"
cat /etc/nginx/conf.d/default.conf
echo "Using the following config.json"
cat /var/www/html/config.json
