version: '3.8'

services:
  # Vue.js app service
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
    command: npm run dev

  # Run ontologies
  owl-server:
    image: node:14
    ports:
      - 3000:3000
    volumes:
      - ./database:/database
      - ./config:/config
    command: >
      sh -c "cd /database && npm install -g @comunica/query-sparql-file && comunica-sparql-file-http ./malware.owl ./cve_gen/CVE-2000-owl.owl ./cve_gen/OVAL_ios.owl -w 6"

