version: '3.7'

services:
  tellstory-fe-prod:
    container_name: tellstory-fe-prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL: ${ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL:-/}
    ports:
      - '8080:80/tcp'
    environment:
      - ATACCAMA_ONE_TELLSTORY_FF_ONE_INTEGRATION
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_APP_BASE_URL
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_API_BASE_URL
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_REALM
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_URL
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_AUTH_KEYCLOAK_CLIENT_ID
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_ONE_INTEGRATION
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_MONITOR_PROJECT
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_DQ_CATALOG_ITEM
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_KEY
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_GOOGLE_API_CLIENT_ID
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_FILTER_RAW
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_DECKGL_KEY
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_FEATURE_DENY_MAPS
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_FEATURE_EXPLORER
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_SHARE_PUBLIC_LINK
      - ATACCAMA_ONE_TELLSTORY_WEBAPP_POSTHOG_API_KEY
